var bankName;
console.log(typeof bankName);
bankName = "Bank Name = SBI Bank";
console.log(bankName);
bankName = "Type of Variable bank name = String";
console.log(bankName);
var mark ="95%";
console.log(mark);
mark ="type of variable mark = string";
console.log(mark);
var Working ="value of isworking is = undefined";
console.log(Working );
Working ="valu of working is = True";
console.log(Working);
var isWorking ="Type of variable isWorking = boolean";
console.log(isWorking);
var count ="Total Count = Hundred and Seven";
console.log(count);
var totalCount ="Type of variable totalCount = string";
console.log(totalCount);
var count ="Total Count = 107";
console.log(count);
var totalCount ="Type of variable total Count = number";
console.log(totalCount);